# Generated by Django 3.0 on 2019-12-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_cat', models.CharField(max_length=100)),
                ('part_detail', models.TextField(null=True)),
            ],
        ),
    ]
