# Generated by Django 3.0 on 2019-12-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='part_photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
